### ISSUE TITLE
Fix FAIL. Reason: Setup failed: The path "artifacts/Vault.json" 

### ISSUE THREAD

**Issue by storming0x** [storming0x/foundry_strategy_mix#28]
Seems foundry config needs this additional setting to work in latest versions

fs_permissions = [{ access = "read", path = "./"}]

A PR can be tested and working with tests after the change has been made

**Comment by qq95538** [comment]
Thank you, sir. I added this line in foundry.toml and 'make test' succeeded.

**Comment by storming0x** [comment]
> Thank you, sir. I added this line in foundry.toml and 'make test' succeeded.

great, will have a PR soon

**Comment by storming0x** [comment]
closing with https://github.com/storming0x/foundry_strategy_mix/pull/30
